# Site settings
title: Zhang Xuanming's homepage
description: Past achievements, current projects and future plans
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Xuanming Zhang
user_description: I am a junior undergraduate student majoring in Information Science.CS/AI. My educational experience covers the Elite Institute of Enginnering Program of Peking University & Chongqing University (The Best Engineering Program in China), University of Bergen (European Ivy League), and now UW-Madison (ISci#11, CS#13). My research/internship experience covers Peking University SEKE Lab (mentors are Prof. Jin Zhi and Prof. Li Ge), Tsinghua University CoAI Lab (mentors are Prof. Huang Minlie, Prof. Yuan Yuan and Prof. Wang Hongning), ByteDance (mentors are Wang Xingnan, Chen Lu, etc.), Zhipu (mentors are Peng Libiao, Prof. Chen Zhuang), Zen-AI (mentor is Yan Libing). I am very grateful to the above institutions, mentors and collaborators.
user_title: Researcher both in Academic and Life
email: xzhang2846@wisc.edu
twitter_username: https://x.com/xuanmingzh36352
github_username:  https://github.com/XMZhangAI
gplus_username:  https://scholar.google.com/citations?view_op=list_works&hl=zh-CN&hl=zh-CN&user=zP5k9lsAAAAJ

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
